# Generated by Django 5.2.15 on 2026-06-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('atividade', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('tipo', models.BooleanField(default=False)),
                ('horas', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField()),
                ('hora', models.CharField(max_length=100)),
                ('horas', models.FloatField()),
                ('curso_alvo', models.CharField(blank=True, max_length=150, null=True)),
                ('palestrante', models.CharField(blank=True, max_length=150, null=True)),
                ('unidade', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('horas_totais', models.FloatField(default=0)),
                ('horas_internas', models.FloatField(default=0)),
                ('horas_externas', models.FloatField(default=0)),
                ('ano_entrada', models.CharField(default='2026', max_length=4)),
                ('periodo', models.CharField(default='2º Período', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('is_funcionario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horas', models.FloatField()),
                ('tipo', models.CharField(max_length=20)),
                ('nome_atividade', models.CharField(max_length=100)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.categoria')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='core.eventos')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.usuario')),
            ],
        ),
    ]
