# Generated by Django 6.0.6 on 2026-06-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_funcionario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
