# Generated by Django 6.0.6 on 2026-06-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_eventos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='local',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='avaliado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_avaliadas', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(default='Pendente', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
